name: Automate Kaggle Notebook Execution

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install kaggle nbconvert wandb numpy pandas scikit-learn

      - name: Authenticate Kaggle API
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: echo "Kaggle API Authenticated"

      - name: Check Directory Structure
        run: |
          echo "Current Directory: $(pwd)"
          ls -l  # Debugging: Show all files

      - name: Push Notebook to Kaggle
        run: |
          kaggle kernels push -p distance_classification  # Use correct relative path

      - name: Download Kaggle Output
        run: |
          kaggle kernels output dhawadedipti/distance-classification -p distance_classification/output/

      - name: Log Results to WandB
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        run: |
          wandb login $WANDB_API_KEY
          python process_results.py  # Ensure this script exists