name: Automate Kaggle Notebook Execution

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install kaggle nbconvert jupyter wandb numpy pandas scikit-learn opencv-python matplotlib scipy

      - name: Authenticate Kaggle API
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          mkdir -p ~/.kaggle
          echo "{\"username\":\"$KAGGLE_USERNAME\",\"key\":\"$KAGGLE_KEY\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
          kaggle --version  # Verify Kaggle CLI is installed

      - name: Debug Directory Structure
        run: |
          echo "Current Directory: $(pwd)"
          ls -l  # Show all files for debugging

      - name: Push Notebook to Kaggle
        run: |
          if [ -f "distance_classification.ipynb" ]; then
            kaggle kernels push -p .
          else
            echo "Error: Notebook 'distance_classification.ipynb' not found!"
            exit 1
          fi

      - name: Execute Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute distance_classification.ipynb --output executed_notebook.ipynb

      - name: Download Kaggle Output
        run: |
          mkdir -p output/
          kaggle kernels output dhawadedipti/distance-classification -p output/

      - name: Log Results to WandB
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        run: |
          wandb login $WANDB_API_KEY
          if [ -f "process_results.py" ]; then
            python process_results.py
          else
            echo "Warning: process_results.py not found, skipping WandB logging."
          fi