name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}  # Inject the secret as an environment variable
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install kaggle nbconvert jupyter wandb numpy pandas scikit-learn opencv-python matplotlib scipy

      - name: Convert Jupyter Notebook to Python
        run: jupyter nbconvert --to script distance_classification.ipynb

      - name: Run Converted Script
        run: python distance_classification.py